afipPAIS = {
    "BURKINA FASO": "101",
    "ARGELIA": "102",
    "BOTSWANA": "103",
    "BURUNDI": "104",
    "CAMERUN": "105",
    "CENTRO AFRICANO, REP.": "107",
    "CONGO REP.POPULAR": "108",
    "ZAIRE": "109",
    "COSTA DE MARFIL": "110",
    "CHAD": "111",
    "BENIN": "112",
    "EGIPTO": "113",
    "GABON": "115",
    "GAMBIA": "116",
    "GHANA": "117",
    "GUINEA": "118",
    "GUINEA ECUATORIAL": "119",
    "KENIA": "120",
    "LESOTHO": "121",
    "REPUBLICA DE LIBERIA (Estado independiente)": "122",
    "LIBIA": "123",
    "MADAGASCAR": "124",
    "MALAWI": "125",
    "MALI": "126",
    "MARRUECOS": "127",
    "REPUBLICA DE MAURICIO": "128",
    "MAURITANIA": "129",
    "NIGER": "130",
    "NIGERIA": "131",
    "ZIMBABWE": "132",
    "RUANDA": "133",
    "SENEGAL": "134",
    "SIERRA LEONA": "135",
    "SOMALIA": "136",
    "REINO DE SWAZILANDIA (Estado independiente)": "137",
    "SUDAN": "138",
    "TANZANIA": "139",
    "TOGO": "140",
    "REPUBLICA TUNECINA": "141",
    "UGANDA": "142",
    "SUDAFRICA, REP. DE": "143",
    "ZAMBIA": "144",
    "POS.BRITANICA (AFRICA)": "145",
    "POS.ESPAÑOLA (AFRICA)": "146",
    "POS.FRANCESA (AFRICA)": "147",
    "POS.PORTUGUESA (AFRICA)": "148",
    "REPUBLICA DE ANGOLA": "149",
    "REPUBLICA DE CABO VERDE (Estado independiente)": "150",
    "MOZAMBIQUE": "151",
    "REPUBLICA DE SEYCHELLES (Estado independiente)": "152",
    "REPUBLICA DE DJIBUTI (Estado independiente)": "153",
    "COMORAS": "155",
    "GUINEA BISSAU": "156",
    "SANTO TOME Y PRINCIPE": "157",
    "NAMIBIA": "158",
    "SUDAFRICA": "159",
    "ERITREA": "160",
    "ETIOPIA": "161",
    "ARGENTINA": "200",
    "BARBADOS (Estado independiente)": "201",
    "BOLIVIA": "202",
    "BRASIL": "203",
    "CANADA": "204",
    "COLOMBIA": "205",
    "COSTA RICA": "206",
    "CUBA": "207",
    "CHILE": "208",
    "DOMINICANA REPUBLICA": "209",
    "ECUADOR": "210",
    "EL SALVADOR": "211",
    "ESTADOS UNIDOS": "212",
    "GUATEMALA": "213",
    "REPUBLICA COOPERATIVA DE GUYANA (Estado independiente)": "214",
    "HAITI": "215",
    "HONDURAS": "216",
    "JAMAICA": "217",
    "MEXICO": "218",
    "NICARAGUA": "219",
    "REPUBLICA DE PANAMA (Estado independiente)": "220",
    "PARAGUAY": "221",
    "PERU": "222",
    "ESTADO LIBRE ASOCIADO DE PUERTO RICO (Estado asoc. a EEUU)": "223",
    "REPUBLICA DE TRINIDAD Y TOBAGO": "224",
    "URUGUAY": "225",
    "VENEZUELA": "226",
    "POS.DANESA (AMERICA)": "228",
    "POS. PAISES BAJOS (AMERICA)": "230",
    "POS.E.E.U.U. (AMERICA)": "231",
    "SURINAME": "232",
    "EL COMMONWEALTH DE DOMINICA (Estado Asociado)": "233",
    "SANTA LUCIA": "234",
    "SAN VICENTE Y LAS GRANADINAS (Estado independiente)": "235",
    "BELICE (Estado independiente)": "236",
    "ANTIGUA Y BARBUDA (Estado independiente)": "237",
    "FEDERACION DE SAN CRISTOBAL (Islas Saint Kitts and Nevis)": "238",
    "COMUNIDAD DE LAS BAHAMAS (Estado independiente)": "239",
    "ESTADO ASOCIADO DE GRANADA (Estado independiente)": "240",
    "AFGANISTAN": "301",
    "ARABIA SAUDITA": "302",
    "ESTADO DE BAHREIN (Estado independiente)": "303",
    "MYANMAR (EX BIRMANIA)": "304",
    "BUTAN": "305",
    "CAMBODYA (EX KAMPUCHEA)": "306",
    "REPUBLICA DEMOCRATICA SOCIALISTA DE SRI LANKA": "307",
    "COREA DEMOCRATICA": "308",
    "COREA REPUBLICANA": "309",
    "CHINA REP.POPULAR": "310",
    "REPUBLICA DE CHIPRE (Estado independiente)": "311",
    "FILIPINAS": "312",
    "TAIWAN": "313",
    "GAZA": "314",
    "INDIA": "315",
    "INDONESIA": "316",
    "IRAK": "317",
    "IRAN": "318",
    "ISRAEL": "319",
    "JAPON": "320",
    "REINO HACHEMITA DE JORDANIA": "321",
    "ESTADO DE QATAR (Estado independiente)": "322",
    "ESTADO DE KUWAIT (Estado independiente)": "323",
    "LAOS": "324",
    "LIBANO": "325",
    "MALASIA": "326",
    "REPUBLICA DE MALDIVAS (Estado independiente)": "327",
    "SULTANATO DE OMAN": "328",
    "MONGOLIA": "329",
    "NEPAL": "330",
    "EMIRATOS ARABES UNIDOS (Estado independiente)": "331",
    "PAKISTAN": "332",
    "SINGAPUR": "333",
    "SIRIA": "334",
    "TAILANDIA": "335",
    "TURQUIA": "336",
    "VIETNAM": "337",
    "MACAO": "344",
    "BANGLADESH": "345",
    "BRUNEI DARUSSALAM (Estado independiente)": "346",
    "REPUBLICA DEL YEMEN": "348",
    "ARMENIA": "349",
    "AZERBAIDZHAN": "350",
    "GEORGIA": "351",
    "KAZAJSTAN": "352",
    "KIRGUISTAN": "353",
    "TAYIKISTAN": "354",
    "TURKMENISTAN": "355",
    "UZBEKISTAN": "356",
    "REPUBLICA DE ALBANIA": "401",
    "ALEMANIA FEDERAL": "402",
    "ALEMANIA ORIENTAL": "403",
    "PRINCIPADO DEL VALLE DE ANDORRA": "404",
    "AUSTRIA": "405",
    "BELGICA": "406",
    "BULGARIA": "407",
    "CHECOSLOVAQUIA": "408",
    "DINAMARCA": "409",
    "ESPAÑA": "410",
    "FINLANDIA": "411",
    "FRANCIA": "412",
    "GRECIA": "413",
    "HUNGRIA": "414",
    "IRLANDA (EIRE)": "415",
    "ISLANDIA": "416",
    "ITALIA": "417",
    "PRINCIPADO DE LIECHTENSTEIN (Estado independiente)": "418",
    "GRAN DUCADO DE LUXEMBURGO": "419",
    "REPUBLICA DE MALTA (Estado independiente)": "420",
    "PRINCIPADO DE MONACO": "421",
    "NORUEGA": "422",
    "PAISES BAJOS": "423",
    "POLONIA": "424",
    "PORTUGAL": "425",
    "REINO UNIDO": "426",
    "RUMANIA": "427",
    "SERENISIMA REPUBLICA DE SAN MARINO (Estado independiente)": "428",
    "SUECIA": "429",
    "SUIZA": "430",
    "VATICANO (SANTA SEDE)": "431",
    "YUGOSLAVIA": "432",
    "HOLANDA": "434",
    "ALEMANIA REP.FED. DE": "438",
    "BIELORUSIA": "439",
    "ESTONIA": "440",
    "LETONIA": "441",
    "LITUANIA": "442",
    "MOLDOVA": "443",
    "RUSIA": "444",
    "UCRANIA": "445",
    "BOSNIA HERZEGOVINA": "446",
    "CROACIA": "447",
    "ESLOVAQUIA": "448",
    "ESLOVENIA": "449",
    "CHECA REPUBLICA": "451",
    "AUSTRALIA": "501",
    "REPUBLICA DE NAURU (Estado independiente)": "503",
    "NUEVA ZELANDIA": "504",
    "REPUBLICA DE VANUATU": "505",
    "SAMOA OCCIDENTAL": "506",
    "POS.AUSTRALIANAS (OCEANIA)": "507",
    "POS.NEOCELANDESAS (OCEANIA)": "510",
    "FIJI, ISLAS": "512",
    "PAPUA, ISLAS": "513",
    "KIRIBATI": "514",
    "MICRONESIA ESTADOS FEDERADOS": "515",
    "PALAU": "516",
    "TUVALU": "517",
    "ISLAS SALOMON": "518",
    "REINO DE TONGA (Estado independiente)": "519",
    "REPUBLICA DE LAS ISLAS MARSHALL (Estado independiente)": "520",
    "ISLAS MARIANAS": "521",
    "U.R.S.S.": "601",
    "ANGUILA (Territorio no autónomo del Reino Unido)": "652",
    "ANTILLAS HOLANDESAS (Territorio de Países Bajos)": "659",
    "ARUBA (Territorio de Países Bajos)": "653",
    "ASCENCION": "662",
    "BERMUDAS (Territorio no autónomo del Reino Unido)": "663",
    "CAMPIONE D@ITALIA": "664",
    "COLONIA DE GIBRALTAR": "665",
    "GROENLANDIA": "666",
    "GUAM (Territorio no autónomo de los EEUU)": "667",
    "HONK KONG (Territorio de China)": "668",
    "ISLAS AZORES": "669",
    "ISLAS DEL CANAL:Guernesey,Jersey,Alderney,G.Stark,L.Sark,etc": "670",
    "ISLAS CAIMAN (Territorio no autónomo del Reino Unido)": "671",
    "ISLA CHRISTMAS": "672",
    "ISLA DE COCOS O KEELING": "673",
    "ISLAS DE COOK (Territorio autónomo asociado a Nueva Zelanda)": "654",
    "ISLA DE MAN (Territorio del Reino Unido)": "676",
    "ISLA DE NORFOLK": "677",
    "ISLAS TURKAS Y CAICOS (Territorio no autónomo del R. Unido)": "678",
    "ISLAS PACIFICO": "679",
    "ISLA DE SAN PEDRO Y MIGUELON": "680",
    "ISLA QESHM": "681",
    "ISLAS VIRGENES BRITANICAS(Territorio no autónomo de R.UNIDO)": "682",
    "ISLAS VIRGENES DE ESTADOS UNIDOS DE AMERICA": "683",
    "LABUAN": "684",
    "MADEIRA (Territorio de Portugal)": "685",
    "MONTSERRAT (Territorio no autónomo del Reino Unido)": "686",
    "NIUE": "687",
    "PATAU": "655",
    "PITCAIRN": "690",
    "POLINESIA FRANCESA (Territorio de Ultramar de Francia)": "656",
    "REGIMEN APLICABLE A LAS SA FINANCIERAS(ley 11.073 de la ROU)": "693",
    "SANTA ELENA": "694",
    "SAMOA AMERICANA (Territorio no autónomo de los EEUU)": "695",
    "ARCHIPIELAGO DE SVBALBARD": "696",
    "TRISTAN DA CUNHA": "697",
    "TRIESTE (Italia)": "698",
    "TOKELAU": "699",
    "ZONA LIBRE DE OSTRAVA (ciudad de la antigua Checoeslovaquia)": "700",
    "OTROS PAISES": "999",
}
